name: Deployment
on:
  push:
    branches:
      - main
      - dev
# global env variables 
env:
  MONGODB_DB_NAME: gha-demo
jobs:
  test:
# use env specific variables 'testing', u can define 'sit', 'pot', ...
# Job level env variables, only access within 'test' job
# for github actions secrets, github actions will always hide this info, not show in any of the workflow logs
    env:
      MONGODB_CLUSTER_ADDRESS: cluster0.15pwqcc.mongodb.net
      MONGODB_USERNAME: ${{secrets.MONGODB_USERNAME}}
      MONGODB_PASSWORD: ${{secrets.MONGODB_PASSWORD}}
      PORT: 8080
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
# reference PORT env variable
# npx wait-on: wait for the server startup...
#        run: npm start & npx wait-on http://127.0.0.1:$PORT
        run: npm start
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "username = ${{env.MONGODB_USERNAME}}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "..."
